EXTENSION = rangefiltersegmentsearch
DATA = sql/rangefiltersegmentsearch--0.0.1.sql
MODULES = rangefiltersegmentsearch  # c module to build

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)